CSV formatter was calling FCSV(output, options.format_options || {}) causing error NoMethodError: undefined method `instance' for Ruport::Formatter::CSV:Class
Changed to FCSV.instance(output, options.format_options || {})